### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by Lynn0213** [yzhangee/NSCaching#1]
请问一下，如果使用CPU跑该代码的话，是不是把代码中的cuda()去掉即可进行正常运行呢？我跑出来结果竟然是损失值一直不变，预测的结果值也不变，期望得到您的回复，谢谢。

**Comment by yzhangee** [comment]
按道理把所有cuda()给拿掉是可以的，cpu上我没试过，运行会很慢。你这种情况应该是参数没有被优化，检查一下是不是删掉了loss.backward()，或者optimizer.step()等。

**Comment by Lynn0213** [comment]
好的，我调整调整，万分感谢

---原始邮件---
发件人: "ZHANG YONGQI"<notifications@github.com&gt;
发送时间: 2020年9月3日(周四) 中午1:43
收件人: "yzhangee/NSCaching"<NSCaching@noreply.github.com&gt;;
抄送: "Lynn0213"<450305320@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [yzhangee/NSCaching] 代码问题 (#1)




 
按道理把所有cuda()给拿掉是可以的，cpu上我没试过，运行会很慢。你这种情况应该是参数没有被优化，检查一下是不是删掉了loss.backward()，或者optimizer.step()等。
